### ISSUE TITLE
rpc error

### ISSUE THREAD

**Issue by imatpro** [NetApp/terraform-provider-netapp-gcp#20] opened 2020-11-10 16:23 UTC
hi, 

I try to add a CVS, 

```
netapp-gcp_volume.static_content will be created
  + resource "netapp-gcp_volume" "static_content" {
      + delete_on_creation_error = false
      + id                       = (known after apply)
      + name                     = "static-content"
      + network                  = "vpc-mdm-network"
      + protocol_types           = [
          + "NFSv3",
        ]
      + region                   = "europe-west1"
      + service_level            = "standard"
      + size                     = 2048
      + type_dp                  = false
      + volume_path              = "static-content"

      + export_policy {
          + rule {
              + access          = "ReadWrite"
              + allowed_clients = "10.28.0.0/21"

              + nfsv3 {
                  + checked = true
                }

              + nfsv4 {
                  + checked = false
                }
            }
          + rule {
              + access          = "ReadWrite"
              + allowed_clients = "10.3.0.0/20"

              + nfsv3 {
                  + checked = true
                }

              + nfsv4 {
                  + checked = false
                }
            }
        }

      + mount_points {
          + export        = (known after apply)
          + protocol_type = (known after apply)
          + server        = (known after apply)
        }

      + snapshot_policy {
          + enabled = false

          + daily_schedule {
              + hour              = (known after apply)
              + minute            = (known after apply)
              + snapshots_to_keep = (known after apply)
            }

          + hourly_schedule {
              + minute            = (known after apply)
              + snapshots_to_keep = (known after apply)
            }

          + monthly_schedule {
              + days_of_month     = (known after apply)
              + hour              = (known after apply)
              + minute            = (known after apply)
              + snapshots_to_keep = (known after apply)
            }

          + weekly_schedule {
              + day               = (known after apply)
              + hour              = (known after apply)
              + minute            = (known after apply)
              + snapshots_to_keep = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

netapp-gcp_volume.static_content: Creating...

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a33b31]
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0:
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: goroutine 15 [running]:
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: github.com/netapp/terraform-provider-netapp-gcp/gcp.resourceGCPVolumeCreate(0xc0002e6bd0, 0x1c88600, 0xc00013e1b0, 0x2, 0x27257a0)
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: 	github.com/netapp/terraform-provider-netapp-gcp/gcp/resource_netapp_gcp_volume.go:400 +0xdd1
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000176e00, 0xc000210320, 0xc0002528e0, 0x1c88600, 0xc00013e1b0, 0x1b4be01, 0xc00022ecd8, 0xc000239f80)
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: 	github.com/hashicorp/terraform@v0.12.28/helper/schema/resource.go:305 +0x365
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000177600, 0xc0002bfa00, 0xc000210320, 0xc0002528e0, 0xc00023caa8, 0xc000100bf0, 0x1b4ddc0)
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: 	github.com/hashicorp/terraform@v0.12.28/helper/schema/provider.go:289 +0x99
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000100c60, 0x1f91b40, 0xc00027e180, 0xc00010a660, 0xc000100c60, 0xc00027e180, 0xc0000f6b78)
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: 	github.com/hashicorp/terraform@v0.12.28/helper/plugin/grpc_provider.go:885 +0x8c4
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1c69ea0, 0xc000100c60, 0x1f91b40, 0xc00027e180, 0xc00010a4e0, 0x0, 0x1f91b40, 0xc00027e180, 0xc000216480, 0x464)
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: 	github.com/hashicorp/terraform@v0.12.28/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001680, 0x1f9d000, 0xc00010d380, 0xc000214000, 0xc000195380, 0x26eb6e0, 0x0, 0x0, 0x0)
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: google.golang.org/grpc.(*Server).handleStream(0xc000001680, 0x1f9d000, 0xc00010d380, 0xc000214000, 0x0)
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000114420, 0xc000001680, 0x1f9d000, 0xc00010d380, 0xc000214000)
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-11-10T16:10:07.823+0100 [DEBUG] plugin.terraform-provider-netapp-gcp_v20.10.0: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2020-11-10T16:10:07.826+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-11-10T16:10:07.826+0100 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/netapp/netapp-gcp/20.10.0/darwin_amd64/terraform-provider-netapp-gcp_v20.10.0 pid=24243 error="exit status 2"
2020/11/10 16:10:07 [DEBUG] netapp-gcp_volume.static_content: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/11/10 16:10:07 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/10 16:10:07 [TRACE] EvalMaybeTainted: netapp-gcp_volume.static_content encountered an error during creation, so it is now marked as tainted
2020/11/10 16:10:07 [TRACE] eval: *terraform.EvalWriteState
2020/11/10 16:10:07 [TRACE] EvalWriteState: removing state object for netapp-gcp_volume.static_content
2020/11/10 16:10:07 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/11/10 16:10:07 [TRACE] EvalApplyProvisioners: netapp-gcp_volume.static_content has no state, so skipping provisioners
2020/11/10 16:10:07 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/10 16:10:07 [TRACE] EvalMaybeTainted: netapp-gcp_volume.static_content encountered an error during creation, so it is now marked as tainted
2020/11/10 16:10:07 [TRACE] eval: *terraform.EvalWriteState
2020/11/10 16:10:07 [TRACE] EvalWriteState: removing state object for netapp-gcp_volume.static_content
2020/11/10 16:10:07 [TRACE] eval: *terraform.EvalIf
2020/11/10 16:10:07 [TRACE] eval: *terraform.EvalIf
2020/11/10 16:10:07 [TRACE] eval: *terraform.EvalWriteDiff
2020/11/10 16:10:07 [TRACE] eval: *terraform.EvalApplyPost
2020/11/10 16:10:07 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/11/10 16:10:07 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/11/10 16:10:07 [TRACE] [walkApply] Exiting eval tree: netapp-gcp_volume.static_content
2020/11/10 16:10:07 [TRACE] vertex "netapp-gcp_volume.static_content": visit complete
2020/11/10 16:10:07 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/netapp/netapp-gcp\"] (close)" errored, so skipping
2020/11/10 16:10:07 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/11/10 16:10:07 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-11-10T16:10:07.979+0100 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Other question : 

I want use on shared VPC network with custom adress range.

how to set the host project and the ip range in the parameters?

Thanks for helping

**Comment by okrause** [comment] 2020-11-10 17:21
Hi,

the last questions you asked sound like you didn't on-board the service first. This provider allows managing CVS volumes after you did the on-boarding. Please see the documentation on how to on-board:
https://cloud.google.com/solutions/partners/netapp-cloud-volumes/before-you-begin-cloud-volumes?hl=en_US
https://cloud.google.com/solutions/partners/netapp-cloud-volumes/setting-up-private-services-access?hl=en_US
This can also be done using the UI. When creating the first volume in the UI, a red box pops up which shows you three gcloud commands to run for on-boarding. The volume creation dialog also gives you the ability to specify host project and desired IP range (RFC1918). Please take care to choose the right VPC and IP range *before* running the three gcloud commands.

**Comment by imatpro** [comment] 2020-11-12 08:27
Hi, thanks for answer

I already create a CVS volume via UI, with correct host project and IP custom range (i have a peering to my hostproject and cvs service) it's working well.

But, i want to create a same with terraform.

`servicemanagement.googleapis.com`  and `servicenetworking.googleapis.com` is enable on my project.

and i have a correct peering and my hostproject : 

```
network: projects/XXXXXXXXXXXX/global/networks/vpc-mdm-network
peering: netapp-sds-nw-customer-peer
reservedPeeringRanges:
- netapp-addresses-sds-vpc-mdm-network
service: services/cloudvolumesgcp-sds-api-network.netapp.com
```

Thanks for helping

**Comment by okrause** [comment] 2020-11-12 13:12
Hmmm, strange. Never saw this.

But: I see you deployed to europe-west1, which is CVS (software based). I only have experience deploying to CVS-Performance (I am somehow a user myself), but I know for sure that the "zone" parameter is required when deploying to CVS-software. Try to specify the correct zone. You will find the zone you deployed to in the CVS UI.

Reference:
https://registry.terraform.io/providers/NetApp/netapp-gcp/latest/docs/resources/volume

**Comment by imatpro** [comment] 2020-11-12 13:46
Thanks for answer, 

I add

```
zone                      = "europe-west1-b" 
shared_vpc_project_number = "XXXXXXXXXXXX"
```
i try with and without this value : 

`storage_class             = "software"`

and same error : 
Error: rpc error: code = Unavailable desc = transport is closing
panic: runtime error: invalid memory address or nil pointer dereference

create via UI : 
<img width="1178" alt="Capture d’écran 2020-11-12 à 14 45 09" src="https://user-images.githubusercontent.com/7237663/98947624-beb43280-24f5-11eb-87d4-6d06bc0d648c.png">

Create via terraform : 
<img width="1178" alt="Capture d’écran 2020-11-12 à 14 55 12" src="https://user-images.githubusercontent.com/7237663/98948779-2919a280-24f7-11eb-8917-3b231476a63e.png">

My complete terraform conf : 
````
terraform {
  required_providers {
    netapp-gcp = {
      source  = "NetApp/netapp-gcp"
      version = "20.10.0"
    }
  }
}

provider "netapp-gcp" {
  project         = "############"
  service_account = local_file.sa_key.filename
}

resource "netapp-gcp_volume" "static_content" {
  provider       = netapp-gcp
  name           = "static-content"
  region         = "europe-west1"
  zone = "europe-west1-b"
  protocol_types = ["NFSv3"]
  shared_vpc_project_number = XXXXXXXXXXX
  network        = "YYYYYYYYYYY"
  size           = 2048
  service_level  = "standard"
  volume_path    = "static-content"
  snapshot_policy {
    enabled = false
  }
  export_policy {
    rule {
      allowed_clients = "10.3.0.0/20"
      access          = "ReadWrite"
      nfsv3 {
        checked = true
      }
      nfsv4 {
        checked = false
      }
    }
    rule {
      allowed_clients = "10.28.0.0/21"
      access          = "ReadWrite"
      nfsv3 {
        checked = true
      }
      nfsv4 {
        checked = false
      }
    }
  }

}
```

Thanks for helping

**Comment by okrause** [comment] 2020-11-12 14:24
Hmm, the provider is crashing. This is really unexpected. Should not happen.

My idea was that it might happen to some invalid input in the TF file (should not happen), but your TF file looks fine, except that you really need to add storage_class = "software" for Belgium, since it is using a different API endpoint than "hardware" (you mentioned that it didn't make a difference, but please specify "software". You might want to try version 20.11.0 instead of 20.10.0, but this is guessing.

@lonico Any suggestions?

**Comment by imatpro** [comment] 2020-11-12 15:39
Hey, 

it' working with 2.11

thank you very much

**Comment by imatpro** [comment] 2020-11-12 15:47
last question, 

provider "netapp-gcp" {
  project         = "YOUR_PROJECT_NUMBER"
  service_account = "YOUR_SERVICE_ACCOUNT"
}

service_account can be a path in a bucket gcp, like gs://mybucket/sa/nepapp.json ?

**Comment by lonico** [comment] 2020-11-12 16:34
great to know it's working with 20.11.
We'll check if there is an issue on our side, or something we already fixed between the 2 versions.

**Comment by okrause** [comment] 2020-11-13 14:08
> Hey,
> 
> it' working with 2.11
> 
> thank you very much

Great to hear! Please be so kind and close the issue if the problem is solved.

**Closed as completed** 2020-11-13 14:21 UTC
